# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Husky Programming Language
email: mishavetl@gmail.com
description: >
    Create an issue on github, contact me or join a gitter char room if you have any questions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://huskylang.github.io" # the base hostname & protocol for your site
github_reponame:  huskylang
example_script: >
    -scrpt greeting


    cs:out('Your name ')

    name <- cs:inl() ;; Take name from stdin


    cs:outl('Hello ', name, '!')
example_script_out: >
    Your name Michael

    Hello Michael!

collections:
    stdlibdoc_modules:
        output: true

    quickstart_parts:
        output: false

    docpages:
        output: true

    mainpages:
        output: true


# Build settings
markdown: kramdown

gems:
    - jekyll-assets

# http://jekyll.github.io/jekyll-assets/
assets:
    # compress:
    #     css: false | true | default - development: false, production: true
    #     js: false | true | default - development: false, production: true
    # cache: false | directory | default: .asset-cache
    prefix: "/assets"
    assets:
        - "*.png"
        - "*.svg"
        - "bundle.css"
    digest: true
    sources:
        - assets
    features:
        liquid: true
